[manager]
show_hidden = true
ratio = [1, 2, 3]
linemode = "size"
sort_by = "natural"
image_delay = 200

[opener]
edit = [
	{ run = 'nvim "$@"', desc = "Neovim", block = true },
	{ run = 'flatpak run com.vivaldi.Vivaldi "$@"', desc = "Browser", orphan = true },
]
play = [
	{ run = 'xdg-open "$@"', desc = "Play", orphan = true },
]
open = [
	{ run = 'xdg-open "$@"', desc = "Open", orphan = true },
	{ run = 'flatpak run com.vivaldi.Vivaldi "$@"', desc = "Browser", orphan = true },
]

[preview]
max_width = 1920
max_height = 1080

[plugin]
  prepend_preloaders = [
    # Replace magick, image, video with mediainfo
    { mime = "{audio,video,image}/*", run = "mediainfo" },
    { mime = "application/subrip", run = "mediainfo" },
  ]
  prepend_previewers = [
    # Replace magick, image, video with mediainfo
    { mime = "{audio,video,image}/*", run = "mediainfo"},
    { mime = "application/subrip", run = "mediainfo" },
  ]
  # There are more extensions which are supported by mediainfo.
  # Just add file's MIME type to `previewers`, `preloaders` above.
  # https://mediaarea.net/en/MediaInfo/Support/Formats
